import 'constant.dart';

class Images {
  static const img_appleLogo = "$BaseUrl/images/caffely/apple.png";
  static const img_applePayLogo = "$BaseUrl/images/caffely/applepay.png";
  static const img_coffeCup = "$BaseUrl/images/caffely/coffee_cup.png";
  static const img_caviar = "$BaseUrl/images/caffely/caviar.png";
  static const img_celebration = "$BaseUrl/images/caffely/celebration.png";
  static const img_chwbus = "$BaseUrl/images/caffely/chowbus.jpg";
  static const img_doordas = "$BaseUrl/images/caffely/doordas.png";
  static const img_facebookLogo = "$BaseUrl/images/caffely/facebook.png";
  static const img_googleLogo = "$BaseUrl/images/caffely/google.png";
  static const img_home1 = "$BaseUrl/images/caffely/home1.jpg";
  static const img_home2 = "$BaseUrl/images/caffely/home2.jpg";
  static const img_hotCoffeeCup = "$BaseUrl/images/caffely/hotCoffee.png";
  static const img_iceCoffeeCup = "$BaseUrl/images/caffely/iceCoffee.png";
  static const img_mastercardLogo = "$BaseUrl/images/caffely/mastercard.png";
  static const img_paypalLogo = "$BaseUrl/images/caffely/paypal.png";
  static const img_qrCode = "$BaseUrl/images/caffely/qr.png";
  static const img_rapido = "$BaseUrl/images/caffely/rapido.png";
  static const img_roadie = "$BaseUrl/images/caffely/roadie.png";
  static const img_twitter = "$BaseUrl/images/caffely/twitter.png";
  static const img_userLocationMarker = "$BaseUrl/images/caffely/user-marker.png";
  static const img_visapay = "$BaseUrl/images/caffely/visapay.png";
  static const img_zifty = "$BaseUrl/images/caffely/zifty.jpg";
  static const img_googleMap = '$BaseUrl/images/caffely/google_map.png';
  static const img_driver =  "$BaseUrl/images/caffely/driver.jpg";
  static const img_user = "$BaseUrl/images/caffely/user.jpg";
  static const img_user2 = "$BaseUrl/images/caffely/user1.jpg";
  static const img_user3 =  "$BaseUrl/images/caffely/user3.jpg";
  static const img_user4 =  "$BaseUrl/images/caffely/user2.jpg";
  static const img_user5 =  "$BaseUrl/images/caffely/user4.jpg";
  static const img_map1 = "$BaseUrl/images/caffely/map1.png";

  static const img_onboarding1 = "$BaseUrl/images/caffely/onboarding1.png";
  static const img_onboarding2 = "$BaseUrl/images/caffely/onboarding2.png";
  static const img_onboarding3 = "$BaseUrl/images/caffely/onboarding3.png";

  static const img_lottie3 = 'assets/animations/3.json';
  static const img_lottie4 = 'assets/animations/4.json';
  static const img_lottie5 = 'assets/animations/5.json';
  static const img_lottie6 = 'assets/animations/6.json';
  static const img_lottieDriver = 'assets/animations/driver.json';
  static const img_lottieEnalbleLocation = 'assets/animations/enable_location.json';
  static const img_lottieLocationLoader = 'assets/animations/location_loader.json';
  static const img_lottieSearchLoader = 'assets/animations/search_loader.json';
  static const img_lottieSplaceLoader = 'assets/animations/splace_loader.json';

  static const img_coffeeCarusel1 = '$BaseUrl/images/caffely/coffee1.jpg';
  static const img_coffeeCarusel2 = '$BaseUrl/images/caffely/coffee2.jpg';
  static const img_coffeeCarusel8 = '$BaseUrl/images/caffely/banner32.jpg';
  static const img_coffeeCarusel11 = '$BaseUrl/images/caffely/sunshine_latte2.jpg';

  static const ic_offer = "assets/icons/account/voucher.svg";
  static const ic_points = "assets/icons/account/points.svg";
  static const ic_ticket = "assets/icons/account/ticket.svg";
  static const ic_coffee = "assets/icons/account/coffee.svg";
  static const ic_location = "assets/icons/account/location.svg";
  static const ic_creaditcard = "assets/icons/account/creadit_card.svg";
  static const ic_user = "assets/icons/account/user.svg";
  static const ic_language = "assets/icons/account/language.svg";
  static const ic_theme = "assets/icons/account/theme.svg";

  static const ic_info = "assets/icons/account/info.svg";
  static const ic_notification = "assets/icons/account/notification.svg";
  static const ic_secuirity = "assets/icons/account/security.svg";
  static const ic_setting = "assets/icons/settings.svg";
  static const ic_favorite = "assets/icons/like.svg";
  static const ic_unfavorite = "assets/icons/unlike.svg";

  static const img_cafe2 = "$BaseUrl/images/caffely/cafeList/img_cafe2.jpg";
  static const img_cafe3 = "$BaseUrl/images/caffely/cafeList/img_cafe3.jpg";
  static const img_cafe4 = "$BaseUrl/images/caffely/cafeList/img_cafe4.jpg";
  static const img_cafe5 = "$BaseUrl/images/caffely/cafeList/img_cafe5.jpg";
  static const img_cafe6 = "$BaseUrl/images/caffely/cafeList/img_cafe6.jpg";
  static const img_cafe7 = "$BaseUrl/images/caffely/cafeList/img_cafe7.jpg";
  static const img_cafe8 = "$BaseUrl/images/caffely/cafeList/img_cafe8.jpg";
  static const img_cafe9 = "$BaseUrl/images/caffely/cafeList/img_cafe9.jpg";
  static const img_cafe10 = "$BaseUrl/images/caffely/cafeList/img_cafe10.jpg";
  static const img_cafe11 = "$BaseUrl/images/caffely/cafeList/img_cafe11.jpg";

  static const img_emoji1 = "$BaseUrl/images/caffely/moods/e1.png";
  static const img_emoji2 = "$BaseUrl/images/caffely/moods/e2.png";
  static const img_emoji3 = "$BaseUrl/images/caffely/moods/e3.png";
  static const img_emoji4 = "$BaseUrl/images/caffely/moods/e4.png";
  static const img_emoji5 = "$BaseUrl/images/caffely/moods/e5.png";
  static const img_emoji6 = "$BaseUrl/images/caffely/moods/e6.png";
  static const img_emoji7 = "$BaseUrl/images/caffely/moods/e7.png";
  static const img_emoji8 = "$BaseUrl/images/caffely/moods/e8.png";
  static const img_emoji9 = "$BaseUrl/images/caffely/moods/e9.png";
  static const img_emoji10 = "$BaseUrl/images/caffely/moods/e10.png";
  static const img_emoji11 = "$BaseUrl/images/caffely/moods/e11.png";
  static const img_emoji12 = "$BaseUrl/images/caffely/moods/e12.png";
  static const img_emoji13 = "$BaseUrl/images/caffely/moods/e13.png";
  static const img_emoji14 = "$BaseUrl/images/caffely/moods/e14.png";
  static const img_emoji15 = "$BaseUrl/images/caffely/moods/e15.png";
  static const img_emoji16 = "$BaseUrl/images/caffely/moods/e16.png";
  static const img_emoji17 = "$BaseUrl/images/caffely/moods/e17.png";
  static const img_emoji18 = "$BaseUrl/images/caffely/moods/e18.png";

  static const ic_appIcon = "assets/icons/coffee_icon.png";
  static const ic_amazon = "assets/icons/amazon.png";
  static const ic_americanExpress = "assets/icons/americanExpress.png";
  static const ic_arebicFlag = "assets/icons/arebic.png";
  static const ic_blueLocationMarker = "assets/icons/bluemarker.png";
  static const ic_callldisconnect = "assets/icons/calldisconnect.png";
  static const ic_frenchFlag = "assets/icons/french.png";
  static const ic_indiaFlag = "assets/icons/india.png";
  static const ic_japanFlag = "assets/icons/japan.png";
  static const ic_jsb2 = "assets/icons/jcbLogo.png";
  static const ic_mandarinFlag = "assets/icons/mandarin.png";
  static const ic_rassiaFlag = "assets/icons/ruccia.png";
  static const ic_spanishFlag = "assets/icons/spanish.png";
  static const ic_currentLocationLogo = "assets/icons/target.png";
  static const ic_ukFlag = "assets/icons/uk.png";
  static const ic_usFlag = "assets/icons/us.png";
  static const ic_visa = "assets/icons/visa.png";
  static const ic_mastercard = "assets/icons/masterCardLogo.png";
  static const ic_driverLocationMarker = "assets/icons/drivermarker.png";
}
